### GET Request to fetch products
GET https://ideal-space-parakeet-wrrj467p9w4fg64-1337.app.github.dev/api/customers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiaWF0IjoxNzMxMDcxODE2LCJleHAiOjE3MzM2NjM4MTZ9.qenjKqTzZgV-qptVGqfsy1GiUtJq7cTMfuyHogKf2gA
